#!/usr/bin/env python
# encoding=utf-8
#
# Copyright © 2011-2013, Martin Tournoij <martin@arp242.net>
# See below for full copyright
#
# http://code.arp242.net/operapass
#
# This just "dumps" the data to the standard output
#
# TODO: Make this a more generic export utilty, exporting to files other
# programs can import (i.e. CSV and the like).
#

from __future__ import print_function
import sys

from operapass import operapass

if __name__ == '__main__':
	print('operapass 1.2, by Martin Tournoij <martin@arp242.net>')
	print('http://code.arp242.net/operapass')
	print('')

	pwfile = operapass.GetPasswordfile()
	passwords = operapass.GetPasswordsDict(pwfile)

	for p in passwords:
		print('-' * 70)
		print(p['url'])
		for k, v in p['fields'].items():
			print('\t%s: %s' % (k, v))
		print('-' * 70)
		print('')

	print('')
	print('Total of %s passwords' % len(passwords))


# The MIT License (MIT)
#
# Copyright © 2011-2013 Martin Tournoij
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# The software is provided "as is", without warranty of any kind, express or
# implied, including but not limited to the warranties of merchantability,
# fitness for a particular purpose and noninfringement. In no event shall the
# authors or copyright holders be liable for any claim, damages or other
# liability, whether in an action of contract, tort or otherwise, arising
# from, out of or in connection with the software or the use or other dealings
# in the software.
